name: CI/CD for Node.js Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
  
    steps:
      - name: Deploy
        run: curl -X POST https://chatbot.koanguyn.org/webhook/deploy?key=${{ secrets.KEY_WEBHOOK }}